source 'https://github.com/CocoaPods/Specs.git'

target 'ASRate_Example', :exclusive => true do
  pod "ASRate", :path => "../"
end

target 'ASRate_Tests', :exclusive => true do
  pod "ASRate", :path => "../"

  
end
